### ISSUE TITLE
How to add href link in spoiler tag?

### ISSUE THREAD

**Issue by counter2015** [unnamed42/hexo-spoiler#1]
I want to add a link in the tag, such as 
```
{% spoiler [text][1] %}

[1]: www.example.com
```
the link is markdown style, but it doesn't work.

Is there any way I can do it ?

Thanks!

**Comment by unnamed42** [comment]
Not possible, `{% spoiler %}` surrounded text is processed by a different markdown renderer instance which does not share data with the post markdown renderer, so it does not know `[1]` means a reference link.

**Comment by counter2015** [comment]
Well, I found a nearly replace way.

In markdown.
```
<a href="https://github.com/unnamed42/hexo-spoiler/issues/1">{% spoiler problem solved %}</a>
```

**Comment by noraj** [comment]
@counter2015 Why not:

```
{% spoiler [text](https://github.com/unnamed42/hexo-spoiler/issues/1) %}
```

**Comment by counter2015** [comment]
> {% spoiler [text](https://github.com/unnamed42/hexo-spoiler/issues/1) %}

Thanks your advice, but it's not work for me.
