### ISSUE TITLE
Vulnerability

### ISSUE THREAD

**Issue by navjotjsingh** [unnamed42/hexo-spoiler#2]
npm audit shows me this

> 
> 
>  Low           │ Regular Expression Denial of Service                         │
> ├───────────────┼──────────────────────────────────────────────────────────────┤
> │ Package       │ braces                                                       │
> ├───────────────┼──────────────────────────────────────────────────────────────┤
> │ Patched in    │ >=2.3.1                                                      │
> ├───────────────┼──────────────────────────────────────────────────────────────┤
> │ Dependency of │ hexo-spoiler                                                 │
> ├───────────────┼──────────────────────────────────────────────────────────────┤
> │ Path          │ hexo-spoiler > hexo-fs > chokidar > anymatch > micromatch >  │
> │               │ braces                                                       │
> ├───────────────┼──────────────────────────────────────────────────────────────┤
> │ More info     │ https://npmjs.com/advisories/786

**Comment by unnamed42** [comment]
Should be fixed now.
