### ISSUE TITLE
Custom options

### ISSUE THREAD

**Issue by noraj** [unnamed42/hexo-spoiler#4]
I could be cool to be able to customize the spoiler.

Eg. instead of a blurry area, set a solid color rectangle and be able to customize the color.

**Comment by unnamed42** [comment]
In the latest version 1.6.1 you can use rectangle by `style:box` and set color by `color:<css-color>`, like 
```
{% spoiler style:box color:red blah blah %}
```
Visit my new README.md for details.

**Comment by noraj** [comment]
Is that possible to configure the default behavior in `_config.yml`? Else having to pass to whole config inline for each block will become a pain when spoiler are used a lot.

**Comment by unnamed42** [comment]
Try 1.7.0, you can config globally in `_config.yml` or for single post in its front-matter.

**Comment by noraj** [comment]
@unnamed42 I'll try it very soon, you're awesome!

**Comment by noraj** [comment]
It's working inline and in front-matter but not from the config file. plugin are usually configured from the hexo `_config.yml` did you read the value from `_config.yml` of the theme?

**Comment by noraj** [comment]
I did hexo clean, and now it works.
