### ISSUE TITLE
[Chore] version

### ISSUE THREAD

**Issue by noraj** [unnamed42/hexo-spoiler#5]
Hi,
A new version was released 1 hour ago,
![image](https://user-images.githubusercontent.com/16578570/91835960-6980b880-ec4a-11ea-8b56-311f94a91f32.png)
Renovate helped me to see the changes: https://app.renovatebot.com/package-diff?name=hexo-spoiler&from=1.5.2&to=1.6.0
but there is not new commit on the git repository?

**Comment by noraj** [comment]
By the way I use those spoilers for my TryHackMe write-ups, to avoid spoiling people that are only looking for hints https://blog.raw.pm/tags/thm/

**Comment by unnamed42** [comment]
@noraj Great showcase, glad to see my plugin helps you.

But there's still some issues, like I can't make `<a>` inactive when not revealed...will be fixed tomorrow.
